"""initial schema

Revision ID: 3ed47f6283bc
Revises: 
Create Date: 2026-07-07 06:21:48.909622

"""
from alembic import op
import sqlalchemy as sa


revision = '3ed47f6283bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('key_id', sa.String(length=16), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('webhook_url', sa.String(length=512), nullable=True),
    sa.Column('lldap_username', sa.String(length=128), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_key_id'), 'agents', ['key_id'], unique=True)
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=True)
    op.create_table('rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Enum('auto_approve', 'auto_deny', name='rule_action'), nullable=False),
    sa.Column('agent_pattern', sa.String(length=128), nullable=False),
    sa.Column('platform', sa.Enum('github', 'homelab', 'a2a', 'google', name='platform'), nullable=False),
    sa.Column('capability_pattern', sa.String(length=128), nullable=False),
    sa.Column('resource_pattern', sa.String(length=512), nullable=False),
    sa.Column('max_duration_secs', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.Enum('github', 'homelab', 'a2a', 'google', name='platform'), nullable=False),
    sa.Column('capability', sa.String(length=128), nullable=False),
    sa.Column('resource', sa.String(length=512), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('requested_duration_secs', sa.Integer(), nullable=False),
    sa.Column('risk_notes', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'llm_evaluating', 'llm_denied', 'awaiting_human', 'approved', 'provisioning', 'granted', 'provision_failed', 'denied', name='request_status'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('decision_source', sa.Enum('policy', 'rule', 'llm', 'human', name='decision_source'), nullable=True),
    sa.Column('decided_by', sa.String(length=128), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('approved_duration_secs', sa.Integer(), nullable=True),
    sa.Column('approved_scope', sa.JSON(), nullable=True),
    sa.Column('approved_resource', sa.String(length=512), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discord_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('discord_message_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_requests_agent_id'), 'access_requests', ['agent_id'], unique=False)
    op.create_index(op.f('ix_access_requests_status'), 'access_requests', ['status'], unique=False)
    op.create_table('grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.Enum('github', 'homelab', 'a2a', 'google', name='platform'), nullable=False),
    sa.Column('capability', sa.String(length=128), nullable=False),
    sa.Column('resource', sa.String(length=512), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'revoked', 'provision_failed', name='grant_status'), nullable=False),
    sa.Column('provisioner_state', sa.JSON(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['access_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grants_active_expiry', 'grants', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_grants_agent_id'), 'grants', ['agent_id'], unique=False)
    op.create_index(op.f('ix_grants_expires_at'), 'grants', ['expires_at'], unique=False)
    op.create_index(op.f('ix_grants_request_id'), 'grants', ['request_id'], unique=True)
    op.create_index(op.f('ix_grants_status'), 'grants', ['status'], unique=False)
    op.create_table('llm_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('suggested_duration_secs', sa.Integer(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['access_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_evaluations_request_id'), 'llm_evaluations', ['request_id'], unique=False)
    op.create_table('a2a_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sender_agent_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_agent_id', sa.String(length=36), nullable=False),
    sa.Column('grant_id', sa.String(length=36), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('delivered_via', sa.String(length=16), nullable=True),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['grants.id'], ),
    sa.ForeignKeyConstraint(['recipient_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['sender_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_a2a_messages_recipient_agent_id'), 'a2a_messages', ['recipient_agent_id'], unique=False)
    op.create_index(op.f('ix_a2a_messages_sender_agent_id'), 'a2a_messages', ['sender_agent_id'], unique=False)
    op.create_table('credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grant_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('value_encrypted', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['grants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_grant_id'), 'credentials', ['grant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credentials_grant_id'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_a2a_messages_sender_agent_id'), table_name='a2a_messages')
    op.drop_index(op.f('ix_a2a_messages_recipient_agent_id'), table_name='a2a_messages')
    op.drop_table('a2a_messages')
    op.drop_index(op.f('ix_llm_evaluations_request_id'), table_name='llm_evaluations')
    op.drop_table('llm_evaluations')
    op.drop_index(op.f('ix_grants_status'), table_name='grants')
    op.drop_index(op.f('ix_grants_request_id'), table_name='grants')
    op.drop_index(op.f('ix_grants_expires_at'), table_name='grants')
    op.drop_index(op.f('ix_grants_agent_id'), table_name='grants')
    op.drop_index('ix_grants_active_expiry', table_name='grants')
    op.drop_table('grants')
    op.drop_index(op.f('ix_access_requests_status'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_agent_id'), table_name='access_requests')
    op.drop_table('access_requests')
    op.drop_table('rules')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_key_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
